### ISSUE TITLE
Interrupts disabled

### ISSUE THREAD

**Issue by gschmidt958** [RobTillaart/FastShiftIn#14]
I see a call to "noInterrupts()', but nowhere do I see a call to re-enable them when done by calling "interrupts()".  Unless I'm missing something, that seems like a problem.  Thanks.

**Comment by RobTillaart** [comment]
Thanks for the question, will look into it later today.

**Comment by RobTillaart** [comment]
Just before the noInterrupts() call there is a line oldSREG = SREG. 
This copies the status register from the  processor including the interrupts bit.

At the end this register is restored, including the interrupts bit.
SREG = oldSREG.

This is the only correct way as it might be that the interrupts were already disabled before calling shiftIn(). The user of the library might have done this for some (unknown) reason.
It would be incorrect to enable the interrupts in the library as that would interfere with that reason and break the expectation that the interrupts are disabled. 

Does this answers your question?

**Comment by gschmidt958** [comment]
Hi, yes I understand, and as you point out, it is the only correct way to do it since it preserves the current state.  So indeed I was missing something as per my original message and I need to become more familiar with the register level.
On another note, I am using your library for an esp32 and it seems to be working well.  I wanted to avoid the 5 microsecond delay that the "standard" ShiftIn() library imposes as I don't believe there is any need to introduce delays when setting the shift register pins and I didn't want to bother writing my own library.  
Thank you for your quick response and explanation!

**Comment by RobTillaart** [comment]
> Thank you for your quick response and explanation!

You're welcome,

Good to hear it works well on the ESP32 for you (I didn't know about that 5 us delay) 

> ...and I didn't want to bother writing my own library.

That's (partially) why I write libraries, so other people have more time to build code on top of it, and go beyond what I can imagine.

If there are no more questions, you may close the issue.

**Comment by gschmidt958** [comment]
Issue was due to my own misunderstanding which Rob clarified, so closing it.
